// Generated from the website's per-product checklist PDFs (public/checklists/*.pdf).
// Only product-specific sections are listed; universal KYC and the profile-based
// income sets live in seed.ts. [productSlug, label, category]
export const PRODUCT_CHECKLIST_ITEMS: [string, string, string][] = [
  // education-loan
  ["education-loan", "10th, 12th & graduation mark sheets", "KYC"],
  ["education-loan", "Entrance exam scorecard — GMAT / GRE / IELTS / TOEFL, etc.", "KYC"],
  ["education-loan", "University admission letter", "KYC"],
  ["education-loan", "If currently working: latest 4 months' salary slips, experience letter & updated CV", "Income proof"],
  ["education-loan", "Ownership proof — latest electricity bill / maintenance receipt", "Property papers"],
  ["education-loan", "Employment proof — Company ID / offer or appointment letter", "Income proof"],
  ["education-loan", "Latest 4 months' salary slips", "Income proof"],
  ["education-loan", "Latest 12 months' salary & savings bank statements", "Bank statement"],
  ["education-loan", "Latest 2 years' Form 16 (Part A & B) and Form 26AS", "Income proof"],
  ["education-loan", "Last 2 years' ITR, if income is taxable", "Income proof"],
  ["education-loan", "Latest 3 years' ITR, balance sheet & P&L, with computation of income — CA-certified/audited, incl. 3CB/3CD, audit report & schedules", "Income proof"],
  ["education-loan", "Latest 12 months' business current & savings bank statements (incl. any existing loan EMI reflection)", "Bank statement"],
  ["education-loan", "Latest 2 years' Form 26AS", "Income proof"],
  ["education-loan", "Latest 12 months' GSTR-3B", "Income proof"],
  ["education-loan", "Other rental income and existing loan details, if any", "Income proof"],
  ["education-loan", "Conveyance deed", "Property papers"],
  ["education-loan", "Sale agreement with chain agreements, if any", "Property papers"],
  ["education-loan", "Society share certificate & registration certificate", "Property papers"],
  ["education-loan", "Property card / title certificate, if applicable", "Property papers"],
  ["education-loan", "CC / OC / sanctioned plan copy", "Property papers"],
  ["education-loan", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  // business-loan
  ["business-loan", "Proof of business ownership", "Business proof"],
  ["business-loan", "Existing loan sanction letter and latest SOA, if any", "Sanction letter"],
  // personal-loan
  ["personal-loan", "Rent agreement + bank statement showing rent credits", "Bank statement"],
  ["personal-loan", "Existing loan sanction letter and latest SOA / EMI details", "Sanction letter"],
  ["personal-loan", "Sanction letter", "Sanction letter"],
  ["personal-loan", "Loan SOA — from beginning to latest date", "Business proof"],
  ["personal-loan", "Foreclosure letter Send clear photos/scans of applicable documents on WhatsApp, sorted by category. This is an indicative list — exact requirements can vary by lender and profile; our team will confirm before login. Growth Capital Services · Loan Solutions from 75+ Banks & NBFCs", "Income proof"],
  // professional-loan
  ["professional-loan", "Professional registration / degree certificate (MBBS, CA, CS, architecture, etc.)", "KYC"],
  ["professional-loan", "Practice licence, if applicable", "Business proof"],
  ["professional-loan", "Clinic/office ownership or rent agreement, for self-employed practice", "Business proof"],
  // balance-transfer
  ["balance-transfer", "Sanction letter", "Sanction letter"],
  ["balance-transfer", "Loan SOA — from beginning to latest date", "Income proof"],
  ["balance-transfer", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["balance-transfer", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["balance-transfer", "Sale agreement with chain agreements, if any", "Property papers"],
  ["balance-transfer", "Society share certificate & registration certificate", "Property papers"],
  ["balance-transfer", "Property card / title certificate, if applicable", "Property papers"],
  ["balance-transfer", "CC / OC / sanctioned plan copy", "Property papers"],
  ["balance-transfer", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  // bank-guarantee
  ["bank-guarantee", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["bank-guarantee", "Sanction letter", "Sanction letter"],
  ["bank-guarantee", "Loan SOA — from beginning to latest date", "Income proof"],
  ["bank-guarantee", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["bank-guarantee", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["bank-guarantee", "Sale agreement with chain agreements, if any", "Property papers"],
  ["bank-guarantee", "Society share certificate & registration certificate", "Property papers"],
  ["bank-guarantee", "Property card / title certificate, if applicable", "Property papers"],
  ["bank-guarantee", "CC / OC / sanctioned plan copy", "Property papers"],
  ["bank-guarantee", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["bank-guarantee", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["bank-guarantee", "Project brochure & MahaRERA registration number", "Property papers"],
  ["bank-guarantee", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["bank-guarantee", "Builder contact person — name & mobile number", "Property papers"],
  // cash-credit
  ["cash-credit", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["cash-credit", "Sanction letter", "Sanction letter"],
  ["cash-credit", "Loan SOA — from beginning to latest date", "Income proof"],
  ["cash-credit", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["cash-credit", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["cash-credit", "Sale agreement with chain agreements, if any", "Property papers"],
  ["cash-credit", "Society share certificate & registration certificate", "Property papers"],
  ["cash-credit", "Property card / title certificate, if applicable", "Property papers"],
  ["cash-credit", "CC / OC / sanctioned plan copy", "Property papers"],
  ["cash-credit", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["cash-credit", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["cash-credit", "Project brochure & MahaRERA registration number", "Property papers"],
  ["cash-credit", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["cash-credit", "Builder contact person — name & mobile number", "Property papers"],
  // cgtmse
  ["cgtmse", "Udyam / MSME registration certificate", "Business proof"],
  ["cgtmse", "Project report / business plan", "Business proof"],
  // dlod
  ["dlod", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["dlod", "Sanction letter", "Sanction letter"],
  ["dlod", "Loan SOA — from beginning to latest date", "Income proof"],
  ["dlod", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["dlod", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["dlod", "Sale agreement with chain agreements, if any", "Property papers"],
  ["dlod", "Society share certificate & registration certificate", "Property papers"],
  ["dlod", "Property card / title certificate, if applicable", "Property papers"],
  ["dlod", "CC / OC / sanctioned plan copy", "Property papers"],
  ["dlod", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  // letter-of-credit
  ["letter-of-credit", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["letter-of-credit", "Sanction letter", "Sanction letter"],
  ["letter-of-credit", "Loan SOA — from beginning to latest date", "Income proof"],
  ["letter-of-credit", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["letter-of-credit", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["letter-of-credit", "Sale agreement with chain agreements, if any", "Property papers"],
  ["letter-of-credit", "Society share certificate & registration certificate", "Property papers"],
  ["letter-of-credit", "Property card / title certificate, if applicable", "Property papers"],
  ["letter-of-credit", "CC / OC / sanctioned plan copy", "Property papers"],
  ["letter-of-credit", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["letter-of-credit", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["letter-of-credit", "Project brochure & MahaRERA registration number", "Property papers"],
  ["letter-of-credit", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["letter-of-credit", "Builder contact person — name & mobile number", "Property papers"],
  // loan-against-mutual-funds
  ["loan-against-mutual-funds", "Latest mutual fund statement / Consolidated Account Statement (CAS)", "Bank statement"],
  ["loan-against-mutual-funds", "Folio details for units to be pledged", "Business proof"],
  ["loan-against-mutual-funds", "Confirmation the scheme is on the lender's approved AMC/fund list", "Business proof"],
  // loan-against-securities
  ["loan-against-securities", "Demat holding statement Latest Consolidated Account Statement (CAS)", "Bank statement"],
  ["loan-against-securities", "Portfolio / policy documents for securities to be pledged Confirmation the securities are on the lender's approved list", "Business proof"],
  // overdraft-limit
  ["overdraft-limit", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["overdraft-limit", "Sanction letter", "Sanction letter"],
  ["overdraft-limit", "Loan SOA — from beginning to latest date", "Income proof"],
  ["overdraft-limit", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["overdraft-limit", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["overdraft-limit", "Sale agreement with chain agreements, if any", "Property papers"],
  ["overdraft-limit", "Society share certificate & registration certificate", "Property papers"],
  ["overdraft-limit", "Property card / title certificate, if applicable", "Property papers"],
  ["overdraft-limit", "CC / OC / sanctioned plan copy", "Property papers"],
  ["overdraft-limit", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["overdraft-limit", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["overdraft-limit", "Project brochure & MahaRERA registration number", "Property papers"],
  ["overdraft-limit", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["overdraft-limit", "Builder contact person — name & mobile number", "Property papers"],
  // private-funding
  ["private-funding", "Private Funding Checklist Fast money when the clock is ticking.", "Business proof"],
  ["private-funding", "Documents You'll Need [ ] KYC (PAN, Aadhaar, address proof) [ ] Property papers (agreement, title chain, tax receipts) [ ] Purpose note and repayment plan", "Property papers"],
  ["private-funding", "Basic Eligibility • Marketable property to offer as security • A credible, time-bound plan to repay or refinance • Ownership papers ready for legal verification", "Property papers"],
  ["private-funding", "Figures above are indicative starting points — your exact eligibility, documentation and pricing depend on the lender's policy and final credit assessment.", "Business proof"],
  ["private-funding", "Ready when you are. Call +91 88280 01700 | growthcs17@gmail.com | CCTV Towers, Andheri-Ghatkopar Rd, Ghatkopar West, Mumbai 400084 Growth Capital Services — Trusted Loan Advisors Since 2017 — Mumbai · Thane · Navi Mumbai · Pune", "Business proof"],
  // project-funding
  ["project-funding", "Detailed project report with cost & sales projections", "Business proof"],
  ["project-funding", "Sanctioned/approved building plans", "Sanction letter"],
  ["project-funding", "Clear, marketable land title documents", "Property papers"],
  ["project-funding", "Proof of developer's own contribution to the project", "Business proof"],
  // working-capital
  ["working-capital", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["working-capital", "Sanction letter", "Sanction letter"],
  ["working-capital", "Loan SOA — from beginning to latest date", "Income proof"],
  ["working-capital", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["working-capital", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["working-capital", "Sale agreement with chain agreements, if any", "Property papers"],
  ["working-capital", "Society share certificate & registration certificate", "Property papers"],
  ["working-capital", "Property card / title certificate, if applicable", "Property papers"],
  ["working-capital", "CC / OC / sanctioned plan copy", "Property papers"],
  ["working-capital", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["working-capital", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["working-capital", "Project brochure & MahaRERA registration number", "Property papers"],
  ["working-capital", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["working-capital", "Builder contact person — name & mobile number", "Property papers"],
  // working-capital-term-loan
  ["working-capital-term-loan", "Existing loan sanction letter and latest SOA / EMI obligation details", "Sanction letter"],
  ["working-capital-term-loan", "Sanction letter", "Sanction letter"],
  ["working-capital-term-loan", "Loan SOA — from beginning to latest date", "Income proof"],
  ["working-capital-term-loan", "LOD (List of Documents) and foreclosure letter", "Income proof"],
  ["working-capital-term-loan", "Draft agreement / agreement for sale, conveyance deed", "Property papers"],
  ["working-capital-term-loan", "Sale agreement with chain agreements, if any", "Property papers"],
  ["working-capital-term-loan", "Society share certificate & registration certificate", "Property papers"],
  ["working-capital-term-loan", "Property card / title certificate, if applicable", "Property papers"],
  ["working-capital-term-loan", "CC / OC / sanctioned plan copy", "Property papers"],
  ["working-capital-term-loan", "Latest electricity, maintenance & property tax receipts", "Property papers"],
  ["working-capital-term-loan", "Draft agreement, builder cost sheet, OCR payment receipts", "Property papers"],
  ["working-capital-term-loan", "Project brochure & MahaRERA registration number", "Property papers"],
  ["working-capital-term-loan", "CC / approved plan copy, APF details & bank list", "Property papers"],
  ["working-capital-term-loan", "Builder contact person — name & mobile number", "Property papers"],
];
